<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Police Emergency Service System</title>
<link rel="stylesheet" href="header_style.css">
</head>

<body>
	<h1>Police Emergency Service System</h1>
	<div id="HeaderStyle">
		<ul>
			<li><a href="login.php"><span>Log In</span></a></li>
			<li><a href="logcall.php"><span>Log Call</span></a></li>
			<li><a href="Update.php"><span>Update</span></a></li>
   			<li><a href="#"><span>Report</span></a></li>
    		<li><a href="#"><span>History</span></a></li>
		</ul>
	</div>
</body>
</html>